# Generated by Django 4.2.4 on 2023-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
