# Generated by Django 4.2.4 on 2023-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_portfolio_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featur_1',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featur_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featur_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
