# Generated by Django 4.2.4 on 2023-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_portfolio_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_e_commerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_web_apps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_websites',
            field=models.BooleanField(default=False),
        ),
    ]
