# Generated by Django 4.2.4 on 2023-09-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_portfolio_is_e_commerce_portfolio_is_updates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='is_e_commerce',
            new_name='is_ecommerce',
        ),
    ]
