# Generated by Django 4.2.4 on 2023-09-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_is_e_commerce_portfolio_is_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio/'),
            preserve_default=False,
        ),
    ]
