# Generated by Django 4.2.4 on 2023-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
